### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by lharv076** [phildionne/citizenbudgetapp.com#5]
Not in the right order

**Comment by phildionne** [comment]
Seems in the right order to me, do you have a specific example of the bug?

![capture d ecran 2016-03-22 a 12 39 59](https://cloud.githubusercontent.com/assets/1047845/13959632/441fc0a6-f02b-11e5-8f75-67db4ffbb5df.png)
![capture d ecran 2016-03-22 a 12 39 54](https://cloud.githubusercontent.com/assets/1047845/13959633/4420839c-f02b-11e5-8bcd-47f67d2f27b7.png)

**Comment by lharv076** [comment]
Ah ok, I was comparing it to the "real" version

http://canmore.citizenbudget.com/?token=pVesR7GBxqTfhiuc5mtA

**Comment by phildionne** [comment]
The data used on the staging server is a few weeks old, it is possible they updated the section's order since then.
